version: "3"
services:
    nginx:
        build: ./docker/nginx
        container_name: nginx
        ports: 
            - 8080:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./site1:/var/www/site1
        networks:
            - default
volumes:
    persistent: